//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudLibraryTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int ID { get; set; }
        public string @string { get; set; }
        public bool @bool { get; set; }
        public int @int { get; set; }
        public double duble { get; set; }
    }
}
